### ISSUE TITLE
Lỗi thêm số điện thoại ở trang edit profile

### ISSUE THREAD

**Issue by MaiManh15** [DucAnh2611/CongNghePhanMem_K2_N2_2022#14]
tại trang edit profile khi thêm số điện thoại có thể thêm số điện thoại dưới 10 số

**Comment by DucAnh2611** [comment]
SDT đủ điều kiện: 
![image](https://user-images.githubusercontent.com/117668851/222962487-b290a059-1d0d-426b-b44b-702ece16abe5.png)
SDT không đủ điều kiện:
- Thiếu số:
![image](https://user-images.githubusercontent.com/117668851/222962520-4b979e35-b2f5-4696-b725-5437fe5b2df0.png)
- Thừa số:
![image](https://user-images.githubusercontent.com/117668851/222962540-539c738c-55c7-46a4-9f01-54a50bd94691.png)
SDT Trùng:
![image](https://user-images.githubusercontent.com/117668851/222962576-29ca19a6-6786-402f-a09f-833b3bef119e.png)
SDT được xác nhận thành công:
![image](https://user-images.githubusercontent.com/117668851/222962599-06bf0e5a-9168-4395-a5c4-a7a4ecbcc622.png)
