### ISSUE TITLE
Lỗi ngày sinh tại trang edit profile

### ISSUE THREAD

**Issue by MaiManh15** [DucAnh2611/CongNghePhanMem_K2_N2_2022#15]
Có để ngày sinh trong tương lai dù chưa đến ngày đấy
VD: hiện tại là 23/02/2023 nhưng có thể thêm ngày sinh ở ngày 23/02/2024

**Comment by DucAnh2611** [comment]
Đã Fix
Chưa thay:
![image](https://user-images.githubusercontent.com/117668851/222962390-6d18e4fc-93f3-47b2-a0e3-89790e950d14.png)
Đã thay, tự động đưa về ngày, giờ hiện tại:
![image](https://user-images.githubusercontent.com/117668851/222962420-42feada0-de2e-45db-bae2-4ec3e2e94d97.png)
