### ISSUE TITLE
Lỗi nút like

### ISSUE THREAD

**Issue by MaiManh15** [DucAnh2611/CongNghePhanMem_K2_N2_2022#16]
khi ấn like thì nút like nảy lên trên sát với ảnh trong bài đăng

**Comment by TienDung2002** [comment]
lỗi giao diện sẽ được khắc phục sau khi hệ thống hoàn thiện

**Comment by DucAnh2611** [comment]
Đã fix xong
![image](https://user-images.githubusercontent.com/117668851/221757173-0e59d2f1-e994-4ef7-bf3e-dda68d9cf36f.png)
![image](https://user-images.githubusercontent.com/117668851/221757237-26c82ee4-76a8-4d6e-9364-697c893953a0.png)
