### ISSUE TITLE
Cập nhật ảnh đại diện lâu

### ISSUE THREAD

**Issue by MaiManh15** [DucAnh2611/CongNghePhanMem_K2_N2_2022#17]
Tốn khá nhiều thời gian
đối với những ảnh 4k thì gần như là không thể thay đổi

**Comment by TienDung2002** [comment]
thời gian cập nhật ảnh mới lên hệ thống cần 1 lúc do lưu lượng bị giới hạn, chúng tôi sẽ cố gắng khắc phục 1 cách nhanh nhất

**Comment by MaiManh15** [comment]
Đã thay đổi:
![image](https://user-images.githubusercontent.com/113126755/223402032-025658a1-813d-4d5a-afe1-1f3bcd87875f.png)
