### ISSUE TITLE
Lỗi về bình luận trong bài đăng

### ISSUE THREAD

**Issue by MaiManh15** [DucAnh2611/CongNghePhanMem_K2_N2_2022#19]
Khi bình luận ở một bài đăng thì ở phần bình luận thì phần bình luận vừa xong bị lặp lại 1 lần

**Comment by TienDung2002** [comment]
Lỗi đang trong quá trình sửa chữa

**Comment by TienDung2002** [comment]
Lỗi đã được fix
Trước khi  comment:
![image](https://user-images.githubusercontent.com/101706065/221917620-e7224fa8-add4-4eeb-83f3-4e9602a19091.png)
Sau khi comment:
![image](https://user-images.githubusercontent.com/101706065/221917687-b8454eb7-1945-45ff-abe3-f943234cf51d.png)
