### ISSUE TITLE
Lỗi không tìm thấy người dùng khác

### ISSUE THREAD

**Issue by MaiManh15** [DucAnh2611/CongNghePhanMem_K2_N2_2022#20]
Khi tìm kiếm ở thanh Search thì không hiện người dùng khác dù tìm theo tên hay id

**Comment by TienDung2002** [comment]
Đã fix
![image](https://user-images.githubusercontent.com/101706065/221917334-c8912492-14de-4f3e-ad3c-7fe0eabbbc26.png)
