### ISSUE TITLE
Đoạn chat không được gửi đi 

### ISSUE THREAD

**Issue by DucAnh2611** [DucAnh2611/CongNghePhanMem_K2_N2_2022#3]

**Comment by DucAnh2611** [comment]
Lỗi do hệ thống chưa phản hồi lại yêu cầu từ phía người dùng dẫn tới mất các thông tin đoạn chat

**Comment by DucAnh2611** [comment]
Not done

**Comment by TienDung2002** [comment]
- Kiểm tra lại hệ thống tiếp nhận yêu cầu ngừi dùng hay chưa
- Kiểm tra hệ thống nhận thông tin nhưng có phản hồi lại không

**Comment by MaiManh15** [comment]
Đã sửa:
![image](https://user-images.githubusercontent.com/113126755/223402392-2cef542a-e53a-46f3-85fe-846957743e2c.png)
![image](https://user-images.githubusercontent.com/113126755/223402490-3e3f821d-9839-4721-ac61-826ac58033cd.png)
![image](https://user-images.githubusercontent.com/113126755/223402609-b8270ff3-2090-45c8-ae4b-690443b87a0e.png)
