### ISSUE TITLE
Tạo unit test cho trang tin nhắn

### ISSUE THREAD

**Issue by DucAnh2611** [DucAnh2611/CongNghePhanMem_K2_N2_2022#5]
Unit test cần bao gồm:

- Tìm kiếm bạn bè -> Chọn bạn bè -> Nhập tin nhắn -> Gửi tin nhắn -> Người bạn dùng được tin nhắn
- Người nhận được tin nhắn -> nhận thông báo -> mở tin nhắn -> đọc và phản hồi thành công 
@TienDung2002

**Comment by TienDung2002** [comment]
Unit đang được chuyển giao cho @DucAnh2611
