### ISSUE TITLE
Không xem được tin nhẵn cũ

### ISSUE THREAD

**Issue by TienDung2002** [DucAnh2611/CongNghePhanMem_K2_N2_2022#6]
Không xem được lịch sử các tin nhắn trong khoảng thời gian cố định trước đó

**Comment by TienDung2002** [comment]
Server hiện đang gặp vấn đề

**Comment by MaiManh15** [comment]
Đã sửa:
![image](https://user-images.githubusercontent.com/113126755/223402207-1305f8c7-b534-40b2-84f4-f03e121d1796.png)
