### ISSUE TITLE
Không xóa hoặc phục hồi được tin nhắn

### ISSUE THREAD

**Issue by TienDung2002** [DucAnh2611/CongNghePhanMem_K2_N2_2022#7]
Tin nhắn gửi đi không thể hoàn tác hoặc phục hồi sau khi đã bị xóa trước đó

**Comment by TienDung2002** [comment]
Mã nguồn khắc phục lỗi đang được thử nghiệm, vui lòng chờ thêm một chút thời gian !

**Comment by TienDung2002** [comment]
chúng tôi vẫn đang cố gắng khắc phục nhanh nhất có thể

**Comment by TienDung2002** [comment]
Lỗi đã được khắc phục

**Comment by DucAnh2611** [comment]
Trước khi xóa tin nhắn:
![image](https://user-images.githubusercontent.com/117668851/222962637-c0a49d6d-3f6b-4ad6-974a-a3c9df7e4acd.png)
Sau khi xóa tin nhắn:
![image](https://user-images.githubusercontent.com/117668851/222962653-e3455c0e-1c41-4a78-b0c9-9ae05ee51b01.png)
